(define (generate-wallpaper xcf filename)
    (let* ((the-image (car (gimp-image-new 4000 4000 RGB)))
        (the-background (car (gimp-layer-new the-image 4000 4000 RGBA-IMAGE "moon-bg" 100 LAYER-MODE-NORMAL)))
        (the-object (car (gimp-file-load-layer RUN-NONINTERACTIVE the-image (string-append (string-append "input/" xcf) ".xcf"))))
        (the-grain (car (gimp-layer-new the-image 4000 4000 RGBA-IMAGE "moon-grain" 100 LAYER-MODE-GRAIN-MERGE)))
        (the-gradient (car (gimp-layer-new the-image 4000 4000 RGBA-IMAGE "moon-gradient" 100 LAYER-MODE-SOFTLIGHT))))
    (gimp-image-insert-layer the-image the-object 0 0)
    (gimp-layer-set-offsets the-object 1150 1150)
    (gimp-context-set-foreground (car (gimp-image-pick-color the-image 0 1150 1150 TRUE TRUE 850)))
    (gimp-image-insert-layer the-image the-background 0 1)
    (gimp-drawable-fill the-background FILL-FOREGROUND)
    (gimp-image-insert-layer the-image the-grain 0 0)
    (gimp-context-set-pattern "Film Grain (Vertical)")
    (gimp-drawable-fill the-grain FILL-PATTERN)
    (plug-in-spread RUN-NONINTERACTIVE the-image the-grain 128 128)
    (gimp-image-insert-layer the-image the-gradient 0 0)
    (gimp-context-set-foreground "black")
    (gimp-edit-blend the-gradient BLEND-FG-TRANSPARENT NORMAL-MODE GRADIENT-RADIAL 100 0 REPEAT-NONE TRUE TRUE 3 0.2 TRUE 2000 2000 0 2000)
    (gimp-image-select-ellipse the-image CHANNEL-OP-ADD 1150 1150 1700 1700)
    (gimp-selection-grow the-image 5)
    (gimp-selection-feather the-image 10)
    (gimp-edit-cut the-gradient)
    (gimp-file-save RUN-NONINTERACTIVE the-image (car (gimp-image-flatten the-image)) (string-append "output/" filename) filename)))
