(define (generate-wallpaper object width height filename)
    (let* (
        (the-image (car (gimp-image-new width height RGB)))
        (the-background (car (gimp-layer-new the-image width height RGBA-IMAGE "bg" 100 LAYER-MODE-NORMAL)))
        (the-object (car (gimp-file-load-layer RUN-NONINTERACTIVE the-image (string-append (string-append "input/" object) ".xcf"))))
        (the-grain (car (gimp-layer-new the-image width height RGBA-IMAGE "grain" 25 LAYER-MODE-GRAIN-MERGE)))
        (the-gradient (car (gimp-layer-new the-image width height RGBA-IMAGE "gradient" 100 LAYER-MODE-SOFTLIGHT)))
        (short-side (if (< width height) width height))
        (object-diameter (if (< short-side 2000) (* short-side 0.85) 1700))
        (object-radius (/ object-diameter 2))
        (half-width (/ width 2))
        (half-height (/ height 2))
        (object-start (- half-width object-radius))
        (object-end (+ half-width object-radius))
        (object-top (- half-height object-radius))
        (object-bottom (+ half-height object-radius))
    )
    (gimp-image-insert-layer the-image the-object 0 0)
    (gimp-context-set-foreground (car (gimp-image-pick-color the-image 0 object-start object-top TRUE TRUE object-radius)))
    (gimp-item-transform-scale the-object object-start object-top object-end object-bottom)
    (gimp-image-insert-layer the-image the-background 0 1)
    (gimp-drawable-fill the-background FILL-FOREGROUND)
    (gimp-image-insert-layer the-image the-grain 0 0)
    (gimp-context-set-pattern "Film Grain (Vertical)")
    (gimp-drawable-fill the-grain FILL-PATTERN)
    (plug-in-spread RUN-NONINTERACTIVE the-image the-grain 128 128)
    (gimp-image-insert-layer the-image the-gradient 0 0)
    (gimp-context-set-foreground "black")
    (gimp-edit-blend the-gradient BLEND-FG-TRANSPARENT NORMAL-MODE GRADIENT-RADIAL 100 0 REPEAT-NONE TRUE TRUE 3 0.2 TRUE half-width half-height 0 half-height)
    (gimp-image-select-ellipse the-image CHANNEL-OP-ADD object-start object-top object-diameter object-diameter)
    (gimp-selection-grow the-image 8)
    (gimp-selection-feather the-image 16)
    (gimp-edit-clear the-gradient)
    (gimp-file-save RUN-NONINTERACTIVE the-image (car (gimp-image-flatten the-image)) filename filename)
    (gimp-image-delete the-image))
)
