(define (generate-demo name-phone name-tablet name-laptop name-desktop filename)
    (let* ((demo (car (gimp-image-new 3096 2064 RGB)))
        (mockup (car (gimp-file-load-layer RUN-NONINTERACTIVE demo "gimp/mockup.xcf")))
        (phone (car (gimp-file-load-layer RUN-NONINTERACTIVE demo (string-append (string-append "samples/375x812/" name-phone) ".png"))))
        (tablet (car (gimp-file-load-layer RUN-NONINTERACTIVE demo (string-append (string-append "samples/768x1024/" name-tablet) ".png"))))
        (laptop (car (gimp-file-load-layer RUN-NONINTERACTIVE demo (string-append (string-append "samples/3072x1920/" name-laptop) ".png"))))
        (desktop (car (gimp-file-load-layer RUN-NONINTERACTIVE demo (string-append (string-append "samples/4096x2304/" name-desktop) ".png")))))
    (gimp-image-insert-layer demo mockup 0 0)
    (gimp-image-insert-layer demo phone 0 1)
    (gimp-item-transform-scale phone 2567 1349 2769 1784)
    (gimp-image-insert-layer demo tablet 0 2)
    (gimp-item-transform-scale tablet 2027 993 2602 1759)
    (gimp-image-insert-layer demo laptop 0 3)
    (gimp-item-transform-scale laptop 349 1028 1439 1709)
    (gimp-image-insert-layer demo desktop 0 4)
    (gimp-item-transform-scale desktop 831 336 2480 1264)
    (gimp-file-save RUN-NONINTERACTIVE demo (car (gimp-image-flatten demo)) filename filename)
    (gimp-image-delete demo)))
